### ISSUE TITLE
How can I install this on Ubuntu?

### ISSUE THREAD

**Issue by mattfox27** [Suven/XBMCMovieList#1]
How would this install on ubuntu?

**Comment by Suven** [comment]
Hey, 

sorry for the late response.

There is no particular ubuntu-build. If you would like to run it on any linux-based os:
- grab the latest build from http://movielist.wbbcoder.de
- unpack it
- look for the file ´MovieList´ which, in the default theme, has a purple icon
- rightclick it, go to the permissions tab and check `allow executing file as programm`
- after that you can run the programm by double-clicking it or right-clicking and then choosing `run`

If that does not work, or nothing happens, please check the terminals output by
- Opening the terminal and typing `cd /path/to/the/tool`
- then executing `./MovieList`

If you receive the error `error while loading shared libraries: libudev.so.0` AND you are running a 64bit-version of Ubuntu, execute the following command:

```
sudo ln -sf /lib/x86_64-linux-gnu/libudev.so.1 /lib/x86_64-linux-gnu/libudev.so.0
```

Let me know if you have any further problems. For the moment being, I will close the issue.

**Comment by mattfox27** [comment]
Cool thanks
