### ISSUE TITLE
Stuck at screen connection

### ISSUE THREAD

**Issue by Aymkdn** [Suven/XBMCMovieList#3]
Hi,

I'm trying to use this tool on Windows 10. I launched the .exe file then clicked on "Go go go" and the program is now asking me the IP of the server and I can enter login/password... But then there is no button or option to go to the next step. I'm just stucked on that screen....

Any idea ?

Thanks

**Comment by Suven** [comment]
Whenever you type there, it tries to connect automaticly and goes to the next screen as soon as it is capable of connecting.

Being stuck means that: either your IP is wrong/not reachable or you didn't allow external access in XBMC.

On the other side this tool wasn't updated in a while as I switched over to Plex :/ It's very possible that this does not work with the recent versions of Kodi.

Which version are you running?

**Comment by Aymkdn** [comment]
Hi.

I'm using Kodi 16.1 .... Finally I found that Kodi already provides a HTML version of the movie library so I'll use it :-)

Thanks anyway
